/**
 * Client side of BROWSER AI FIRST question generation.
 *
 * Called right before a game starts. It asks the server for the same prompts
 * the server would use, runs them through the on-device model pool, validates
 * each batch locally (complete, parseable, right number of well-formed items)
 * and hands the surviving batches back to the server. Anything the device could
 * not produce is simply generated by the existing API Manager providers during
 * the normal start flow — so this can always fail silently.
 */
import { hasDeviceAi, looksComplete, runDeviceText } from "./browser-ai";
import { deviceQuestionPlanFn, deviceQuestionSubmitFn } from "./device-ai.functions";

export type DeviceQuestionTask = "quiz" | "mystery" | "god";

type Row = Record<string, unknown>;

/** A batch is only usable when EVERY item in it is complete and well formed. */
function batchIsValid(text: string, need: number): boolean {
  if (!looksComplete(text)) return false;
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start < 0 || end <= start) return false;
  let parsed: unknown;
  try {
    parsed = JSON.parse(text.slice(start, end + 1));
  } catch {
    return false;
  }
  const obj = (parsed ?? {}) as { questions?: unknown; cases?: unknown };
  const rows = (Array.isArray(obj.questions) ? obj.questions : obj.cases) as Row[] | undefined;
  if (!Array.isArray(rows) || rows.length < need) return false;
  return rows.slice(0, need).every((r) => {
    if (!r || typeof r !== "object") return false;
    const q = String(r["question"] ?? "").trim();
    const options = r["options"];
    const idx = Number(r["correctIndex"]);
    return (
      q.length > 8 &&
      Array.isArray(options) &&
      options.length === 4 &&
      options.every((o) => String(o ?? "").trim().length > 0) &&
      Number.isInteger(idx) &&
      idx >= 0 &&
      idx <= 3
    );
  });
}

/**
 * Best effort. Resolves with the number of batches accepted by the server
 * (0 when the device has no AI, or nothing passed validation).
 */
export async function prepareDeviceQuestions(
  token: string,
  task: DeviceQuestionTask,
  count: number,
): Promise<number> {
  try {
    if (!(await hasDeviceAi())) return 0;
    const plan = await deviceQuestionPlanFn({ data: { token, task, count } });
    if (!plan?.batches?.length) return 0;

    const batches: string[] = [];
    for (const batch of plan.batches) {
      const result = await runDeviceText({
        system: plan.system,
        user: batch.user,
        validate: (text) => batchIsValid(text, batch.need),
      });
      // A failed batch is not retried on the same models; the server fills the gap.
      if (result?.text) batches.push(result.text);
    }
    if (!batches.length) return 0;

    const saved = await deviceQuestionSubmitFn({ data: { token, task, batches } });
    return Number(saved?.stored ?? 0);
  } catch {
    return 0;
  }
}
