/**
 * Short-lived holding area for question batches generated by the player's own
 * device (browser AI). The client generates, the server validates.
 *
 * Why a table and not a function argument: the generators already receive a
 * `guestId`, so pulling the pending batches here keeps every existing game
 * engine (Crorepati, Mega, Events, Mystery, GOD MASTER) and its start server
 * function completely untouched.
 *
 * Nothing here is trusted: a batch is only ever raw model text that the
 * existing server-side parsing, validation and fact-checking must still accept.
 */
import { db } from "./guest.server";

const TABLE = "device_ai_batches";
/** Batches older than this are stale and ignored. */
const MAX_AGE_MS = 15 * 60 * 1000;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const sdb = () => db() as any;

export type DeviceTask = "quiz" | "mystery" | "god";

export function isDeviceTask(value: unknown): value is DeviceTask {
  return value === "quiz" || value === "mystery" || value === "god";
}

export async function storeDeviceBatches(
  guestId: string,
  task: DeviceTask,
  batches: string[],
): Promise<number> {
  const rows = batches
    .map((raw) => String(raw ?? "").trim())
    .filter((raw) => raw.length > 0 && raw.length < 60_000)
    .slice(0, 12)
    .map((raw) => ({ guest_id: guestId, task, raw }));
  if (!rows.length) return 0;
  // Replace anything pending for this task so a stale attempt cannot leak in.
  await sdb().from(TABLE).delete().eq("guest_id", guestId).eq("task", task);
  const { error } = await sdb().from(TABLE).insert(rows);
  if (error) return 0;
  return rows.length;
}

/** Reads and consumes the pending batches for one guest + task. */
export async function takeDeviceBatches(
  guestId: string,
  task: DeviceTask,
): Promise<string[]> {
  try {
    const { data } = await sdb()
      .from(TABLE)
      .select("id, raw, created_at")
      .eq("guest_id", guestId)
      .eq("task", task)
      .order("created_at", { ascending: true })
      .limit(12);
    const rows = (data ?? []) as Array<Record<string, unknown>>;
    if (!rows.length) return [];
    await sdb()
      .from(TABLE)
      .delete()
      .in("id", rows.map((r) => r["id"]));
    const now = Date.now();
    return rows
      .filter((r) => now - new Date(String(r["created_at"])).getTime() < MAX_AGE_MS)
      .map((r) => String(r["raw"] ?? ""))
      .filter(Boolean);
  } catch {
    return [];
  }
}
